name: Build Windows Container Image

on:
  push:
    branches: [ post-containerisation ]
  pull_request:
    branches: [ post-containerisation ]
  workflow_dispatch:
  
env:
  dockerfilePath: 'MvcMusicStore-Completed\CIDockefile'
  USER: ${{ secrets.ACR_USER }}
  TOKEN: ${{ secrets.ACR_SECRET }}
  REPOSITORY: ${{ secrets.ACR_INSTANCE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy-to-azure:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      - name: Build and push an image to container registry
        run: |
          more ${{ github.workspace }}\$env:dockerfilePath
          docker login $env:REPOSITORY -u $env:USER -p $env:TOKEN
          docker build --file=$env:dockerfilePath -t ${{ secrets.ACR_INSTANCE }}/${{ secrets.IMAGE_NAME }}:${{ github.run_id  }} .
          docker image push ${{ secrets.ACR_ACR_INSTANCE }}/${{ secrets.IMAGE_NAME }}:${{ github.run_id  }}
          docker logout
